
name: Build lxml for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build lxml cp313-manylinux_aarch64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'lxml/lxml'
          ref: 'lxml-6.1.0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BEFORE_ALL: "apt-get update && apt-get install -y libxml2-dev libxslt1-dev"
          CIBW_BUILD: cp313-manylinux_aarch64
          CIBW_ARCHS_LINUX: aarch64
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
